- name: List security patches on Ubuntu
  hosts: syd
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false

    - name: List security updates
      ansible.builtin.shell: |
        apt list --upgradable 2>/dev/null | grep security || true
      register: security_updates
      changed_when: false

    - name: Show security updates
      ansible.builtin.debug:
        msg: |
          Security updates available:   
          {% if security_updates.stdout_lines | length > 0 %}
          {{ security_updates.stdout_lines }}
          {% else %}
          None
          {% endif %}

    - name: Send security patch collection to user
      community.general.mail:
        host: mail.dolby.com
        port: 25
        sender: security-update-check@dolby.com
        to: huwu@dolby.com
        subject: "Security patches for {{ inventory_hostname }}"
        body: |
          {% if security_updates.stdout_lines | length > 0 %}
          Available security updates for {{ inventory_hostname }}:
          
          
          {{ security_updates.stdout_lines }}
          {% else %}
          No security update available for {{ inventory_hostname }}.
          {% endif %}
